lobby:
  make-public-message: "禁止设置为公开"
role:
  unknown:
    name: "未知"
    description: "当你未被分配职业或者其他特殊情况，你会是这个职业"
    long-description: "当你未被分配职业或者其他特殊情况，你会是这个职业"
  global:
    max-num: "最大职业数量"
    allow-start-meeting: "允许启动会议"
    allow-report-body: "允许报告尸体"
    kill-cooldown: "击杀冷却时间"
    no-more-description: "没有详细信息"
    role-code: "职业特征码"
  impostor:
    impostor:
      name: "伪装者"
      description: "击杀船员，造成破坏"
      long-description: "只是内鬼而已"
    cleaner:
      name: "清洁工"
      description: "清除作案痕迹"
      long-description: "清洁工可以清理船员的尸体。清洁工可以击杀，但是击杀和清理共用冷却"
      clean-cd: "清理尸体冷却"
  crewmate:
    crewmate:
      name: "船员"
      description: "找出伪装者，投出内鬼"
      long-description: "只是船员罢了"
    bait:
      name: "诱饵"
      description: "愿者上钩"
      long-description: "被击杀时，凶手自动报告鸡腿"
      killer-report-delay: "凶手自报延迟"
      warn-killer: "闪光警告凶手"
    sheriff:
      name: "警长"
      description: "任何邪恶，终将绳之以法"
      long-description: "可执法淘汰内鬼阵营，中立第三方或中立杀手玩家，尝试执法船员阵营玩家会直接出局。"
    vigilante:
      name: "侠客"
      description: "行侠仗义！"
      long-description: "你拥有一次击杀机会，当船员数量小于等于设定值时你会额外获得一次击杀机会"
      min-crewmate-number: "给予额外击杀机会的最小船员数量"
    soul-hunter:
      name: "灵魂猎手"
      description: "从地狱归来，将邪恶一同带去"
      long-description: "拥有一次无代价击杀。被击杀后指定秒在鸡腿处复活(如果鸡腿还存在的话)并获得一次执法机会，下轮会议召开时将立刻出局。"
      revive-after: "复活秒数"
    technician:
      name: "技术员"
      description: "解决飞船的一切疑难杂症"
      long-description: "可以进行2次修复，立刻结束破坏或封锁。完成所有任务后可以使用通风口。"
  neutral:
    jester:
      name: "小丑"
      description: "承受一切诋毁，然后放声大笑"
      long-description: "被投票放逐直接获胜"
  sub-roles:
    guesser:
      name: "赌怪"
      description: "生命就是豪赌"
      long-description: "你可以在会议上猜测他人的职业，但如果猜测失败你将会自杀"
      max-guess-time: "最大猜测次数"
      guess-continuously: "连续赌注"
      guess-enabled-roles-only: "仅能赌注启用职业"
      can-guess-sub-roles: "启用赌注副职业"
camp:
  unknown:
    name: "未知阵营"
    description: "未知的阵营"
  impostor:
    name: "伪装者阵营"
    description: "杀死船员"
  neutral:
    name: "中立阵营"
    description: "掌握好权重"
  crewmate:
    name: "船员阵营"
    description: "完成任务，找出内鬼"
  addon: "附加职业"
game-setting:
  view-description:
    general: "预览游戏大厅的常规设置。"
    role: "预览游戏大厅的职业设置。"
  general:
    title: "COG设置"
    load-preset: "加载预设"
    save-preset: "保存预设"
    debug-mode: "<color=#9AFF00>调试模式</color>"
    max-sub-role-number: "最大副职业数量"
    max-neutral-number: "最大中立数目"
option:
  main:
    cog-options: "COG选项"
    load-custom-lang: "加载自定义语言文件"
    unload-mod:
      name: "临时禁用模组"
      success: "模组已成功被临时禁用！\n如果您仍想要继续游玩模组，请重启游戏"
      error-in-game: "请先离开本局游戏再进行操作"
    github: "Github"
    qq: "QQ"
    discord: "Discord"
    update-button-string: "检查更新"
    update:
      up-to-date: "你已经更新到最新版本"
      non-check: "未能找到最新版本"
      fetched: "搜索到最新版：%version%\r\n%description%\r\n是否安装？"
  enable: "<color=#5DB927>开启</color>"
  disable: "<color=#F20D0D>关闭</color>"
action:
  kill: "击杀"
  clean: "清理"
game:
  end:
    show-players-roles-message: "玩家职业:"
    wins:
      impostor: "伪装者胜利"
      crewmate: "船员胜利"
      neutral: "%player% 胜利"
  survival-data:
    alive: "存活"
    disconnected: "掉线"
    default: "死亡"
    unknown: "未知"
  exile:
    default: "%player% 是 %role%。"
    alive-player-info: "剩余 %crew% 个船员， %neutral% 个中立， %imp% 个内鬼。"
  chat:
    system-message: "<b>【系统消息】</b>\0"